# Generated by Django 5.2 on 2026-06-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stoporder",
            name="order_mode",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="stoporder",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
