# Generated by Django 5.2 on 2026-06-19 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0002_alter_stoporder_order_mode_alter_stoporder_price"),
        ("trading", "0002_baseuser_capital_inventory"),
    ]

    operations = []
